import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Ensure all weights are included
});

export const metadata: Metadata = {
  title: "Voting smart contract",
  description: "Generated by Delassus Félix & Gillet Victor",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} font-sans`}>
      <body
        className={`bg-gray-100`}
      >
        <nav className="bg-gray-800 p-4">
          <ul className="flex items-center space-x-4">
            <li>
              <a href="/" className="flex items-center gap-2 text-2xl text-white hover:text-gray-400">
              <Image src="/images/votereum_blue_allonge.png" alt="logo" width={200} height={80} />
              </a>
            </li>
            {/*<li>
              <a href="/about" className="text-white hover:text-gray-400">
                About
              </a>
            </li>
            <li>
              <a href="/contact" className="text-white hover:text-gray-400">
                Contact
              </a>
            </li>*/}  
          </ul>
        </nav>
        <div className="p-4">{children}</div>
      </body>
    </html>
  );
}
